# Generated by Django 3.0.5 on 2020-04-29 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('conteudo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25, unique=True)),
                ('icone_menu', models.CharField(max_length=255)),
                ('imagem_parallax', models.CharField(max_length=255)),
                ('form_contato', models.BooleanField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('conteudo', models.TextField()),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Sessao')),
            ],
        ),
        migrations.CreateModel(
            name='Modal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('conteudo', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Sessao'),
        ),
    ]
