# Generated by Django 3.0.5 on 2020-04-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessao',
            options={'verbose_name_plural': 'Sessoes'},
        ),
        migrations.AlterField(
            model_name='sessao',
            name='icone_menu',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='imagem_parallax',
            field=models.CharField(max_length=512),
        ),
    ]
