# Generated by Django 3.0.5 on 2020-04-30 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200429_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='modal',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modal',
            name='titulo',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
