# Generated by Django 3.0.5 on 2020-04-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_link_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.CharField(max_length=512),
        ),
    ]
