# Generated by Django 3.0.5 on 2020-04-30 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_perfil_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='icone',
        ),
        migrations.RemoveField(
            model_name='link',
            name='pre_texto',
        ),
        migrations.AddField(
            model_name='link',
            name='referencia',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='tipo',
            field=models.CharField(choices=[('TX', 'TEXTO'), ('IC', 'ICONE')], default='IC', max_length=3),
        ),
    ]
