# Generated by Django 3.0.5 on 2020-05-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200430_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessao',
            name='form_contato',
        ),
    ]
