# Generated by Django 3.0.5 on 2020-05-09 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_sessao_form_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modal',
            name='titulo',
            field=models.CharField(max_length=25),
        ),
    ]
