# Generated by Django 3.0.5 on 2020-05-17 14:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20200509_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='modal',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='texto',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
